// AUTO-GENERATED by scripts/generate_ts_schemas.py — do not edit by hand.
// Source of truth: apps/api/app/core/events/*.py


export enum EventType {
  PROJECT_CREATED = "project.created",
  PROJECT_ARCHIVED = "project.archived",
  TASK_CREATED = "task.created",
  TASK_ASSIGNED = "task.assigned",
  TASK_STARTED = "task.started",
  TASK_COMPLETED = "task.completed",
  TASK_FAILED = "task.failed",
  TASK_RETRIED = "task.retried",
  TASK_CANCELLED = "task.cancelled",
  TASK_STATE_CHANGED = "task.state_changed",
  TASK_RECOVERED = "task.recovered",
  BUDGET_EXCEEDED = "task.budget_exceeded",
  AGENT_CREATED = "agent.created",
  AGENT_STARTED = "agent.started",
  AGENT_STOPPED = "agent.stopped",
  AGENT_STATE_CHANGED = "agent.state_changed",
  AGENT_PROFILE_UPDATED = "agent.profile_updated",
  CODING_STARTED = "agent.coding_started",
  AGENT_RESOLVED = "agent.resolved",
  AGENT_HIRED = "agent.hired",
  SELF_CORRECTION_TRIGGERED = "agent.self_correction_triggered",
  WORKSPACE_INITIALIZED = "workspace.initialized",
  CODE_CHANGED = "code.changed",
  BRANCH_MERGED = "branch.merged",
  MODEL_CHANGED = "model.changed",
  PROVIDER_CHANGED = "provider.changed",
  PROVIDER_RETRIED = "provider.retried",
  REVIEW_STARTED = "workflow.review_started",
  REVIEW_COMPLETED = "workflow.review_completed",
  BUG_FOUND = "workflow.bug_found",
  DEPLOYMENT_STARTED = "workflow.deployment_started",
  DEPLOYMENT_COMPLETED = "workflow.deployment_completed",
  DEPLOYMENT_FAILED = "workflow.deployment_failed",
  EXECUTION_STARTED = "execution.started",
  EXECUTION_COMPLETED = "execution.completed",
  APPROVAL_REQUESTED = "approval.requested",
  APPROVAL_GRANTED = "approval.granted",
  APPROVAL_REJECTED = "approval.rejected",
  APPROVAL_CHANGES_REQUESTED = "approval.changes_requested",
  SYSTEM_HEARTBEAT = "system.heartbeat",
  CONVERSATION_MESSAGE = "conversation.message",
  CONVERSATION_MESSAGE_DELTA = "conversation.message.delta",
  SPECIFICATION_REQUESTED = "specification.requested",
  SPECIFICATION_TURN_POSTED = "specification.turn_posted",
  SPECIFICATION_CLARIFICATION_REQUESTED = "specification.clarification_requested",
  SPECIFICATION_CLARIFICATION_ANSWERED = "specification.clarification_answered",
  SPECIFICATION_READY = "specification.ready_for_review",
  SPECIFICATION_APPROVED = "specification.approved",
  SPECIFICATION_REVISION_REQUESTED = "specification.revision_requested",
  SPECIFICATION_REJECTED = "specification.rejected",
  SPECIFICATION_CANCELLED = "specification.cancelled",
  SPECIFICATION_FAILED = "specification.failed",
  MEMORY_RECORDED = "memory.recorded",
  MEMORY_RECALLED = "memory.recalled",
}

export enum AgentState {
  IDLE = "idle",
  ASSIGNED = "assigned",
  PLANNING = "planning",
  WORKING = "working",
  WAITING_REVIEW = "waiting_review",
  BLOCKED = "blocked",
  COMPLETED = "completed",
  FAILED = "failed",
}

export enum TaskState {
  CREATED = "created",
  ASSIGNED = "assigned",
  IN_PROGRESS = "in_progress",
  IN_REVIEW = "in_review",
  PENDING_APPROVAL = "pending_approval",
  COMPLETED = "completed",
  FAILED = "failed",
  RETRYING = "retrying",
  CANCELLED = "cancelled",
  BLOCKED = "blocked",
}

export enum Personality {
  PROFESSIONAL = "professional",
  FRIENDLY = "friendly",
  DIRECT = "direct",
  CONSERVATIVE = "conservative",
}

export enum WorkingStyle {
  FAST = "fast",
  BALANCED = "balanced",
  DETAIL_ORIENTED = "detail_oriented",
}

export enum DecisionStyle {
  RISK_AVOIDING = "risk_avoiding",
  BALANCED = "balanced",
  EXPERIMENTAL = "experimental",
}

export enum StatusWord {
  PLANNING = "planning",
  DEVELOPING = "developing",
  REVIEWING = "reviewing",
  NEEDS_DECISION = "needs_decision",
  BLOCKED = "blocked",
  COMPLETED = "completed",
  FAILED = "failed",
  CANCELLED = "cancelled",
  IDLE = "idle",
}

export interface Actor {
  role: "ceo" | "employee" | "system";
  id: string;
  name: string;
}

export interface AgentProfile {
  name: string;
  role: string;
  personality: Personality;
  working_style: WorkingStyle;
  decision_style: DecisionStyle;
  custom_instructions: string;
  model_ref?: string | null;
  skill_template_key: string;
}

export interface CheckOutcome {
  name: string;
  status: "passed" | "failed" | "could_not_run";
  duration_seconds: number;
  output: string;
}

export interface ProjectCreatedPayload {
  name: string;
}

export interface ProjectArchivedPayload {
}

export interface TaskCreatedPayload {
  task_id: string;
  title: string;
  priority: string;
}

export interface TaskAssignedPayload {
  task_id: string;
  agent_id: string;
  attempt: number;
}

export interface TaskStartedPayload {
  task_id: string;
  agent_id: string;
}

export interface TaskCompletedPayload {
  task_id: string;
}

export interface TaskFailedPayload {
  task_id: string;
  reason_code?: string | null;
}

export interface TaskRetriedPayload {
  task_id: string;
  attempt: number;
}

export interface TaskCancelledPayload {
  task_id: string;
}

export interface TaskStateChangedPayload {
  task_id: string;
  previous_state: TaskState;
  new_state: TaskState;
}

export interface TaskRecoveredPayload {
  task_id: string;
  previous_state: TaskState;
}

export interface BudgetExceededPayload {
  task_id: string;
  limit_kind: "tokens" | "usd" | "seconds";
  limit_value: number;
  observed_value: number;
  stage: string;
}

export interface AgentCreatedPayload {
  agent_id: string;
  role: string;
  name: string;
}

export interface AgentStartedPayload {
  agent_id: string;
  role: string;
}

export interface AgentStoppedPayload {
  agent_id: string;
}

export interface AgentStateChangedPayload {
  agent_id: string;
  previous_state: AgentState;
  new_state: AgentState;
}

export interface AgentProfileUpdatedPayload {
  agent_id: string;
  changed_fields: string[];
}

export interface CodingStartedPayload {
  agent_id: string;
  task_id: string;
}

export interface AgentResolvedPayload {
  role_key: string;
  agent_id: string;
  rule: "idle" | "no_idle_fallback";
}

export interface AgentHiredPayload {
  agent_id: string;
  role_key: string;
  model_ref: string | null;
  skill_template_key: string;
}

export interface AgentSelfCorrectionTriggeredPayload {
  task_id: string;
  agent_id: string;
  attempts_permitted: number;
}

export interface WorkspaceInitializedPayload {
}

export interface CodeChangedPayload {
  branch_name: string;
  commit_sha: string;
  files_added: number;
  files_modified: number;
  files_deleted: number;
  additions: number;
  deletions: number;
  summary: string;
}

export interface BranchMergedPayload {
  branch_name: string;
  commit_sha: string;
}

export interface ModelChangedPayload {
  role: string;
  previous_model: string;
  new_model: string;
}

export interface ProviderChangedPayload {
  previous_provider: string;
  new_provider: string;
}

export interface ProviderRetriedPayload {
  provider: string;
  attempt: number;
}

export interface ReviewStartedPayload {
  task_id: string;
  reviewer_agent_id: string;
}

export interface ReviewCompletedPayload {
  task_id: string;
  outcome: string;
  sections: Record<string, string>;
}

export interface BugFoundPayload {
  task_id: string;
  description: string;
}

export interface DeploymentStartedPayload {
  deployment_id: string;
}

export interface DeploymentCompletedPayload {
  deployment_id: string;
}

export interface DeploymentFailedPayload {
  deployment_id: string;
}

export interface ExecutionStartedPayload {
  task_id: string;
  check_names: string[];
}

export interface ExecutionCompletedPayload {
  task_id: string;
  results: CheckOutcome[];
  passed_count: number;
  total_count: number;
}

export interface ApprovalRequestedPayload {
  approval_id: string;
  task_id: string;
  subject: string;
}

export interface ApprovalGrantedPayload {
  approval_id: string;
}

export interface ApprovalRejectedPayload {
  approval_id: string;
}

export interface ApprovalChangesRequestedPayload {
  approval_id: string;
}

export interface SystemHeartbeatPayload {
}

export interface ConversationMessagePayload {
  text: string;
  agent_id?: string | null;
  task_id?: string | null;
}

export interface ConversationMessageDeltaPayload {
  text: string;
  agent_id?: string | null;
  task_id?: string | null;
  done: boolean;
}

export interface SpecificationRequestedPayload {
  specification_id: string;
  pm_agent_id: string;
  cto_agent_id: string;
}

export interface SpecificationTurnPostedPayload {
  specification_id: string;
  turn_index: number;
  role_key: string | null;
  agent_id: string | null;
  kind: string;
}

export interface SpecificationClarificationRequestedPayload {
  specification_id: string;
  questions: string[];
}

export interface SpecificationClarificationAnsweredPayload {
  specification_id: string;
}

export interface SpecificationReadyPayload {
  specification_id: string;
  version: number;
}

export interface SpecificationApprovedPayload {
  specification_id: string;
  version: number;
}

export interface SpecificationRevisionRequestedPayload {
  specification_id: string;
  version: number;
}

export interface SpecificationRejectedPayload {
  specification_id: string;
}

export interface SpecificationCancelledPayload {
  specification_id: string;
}

export interface SpecificationFailedPayload {
  specification_id: string;
  reason: string;
}

export interface MemoryRecordedPayload {
  memory_id: string;
  category: string;
  source_event_id: string;
  source_task_id?: string | null;
  source_specification_id?: string | null;
}

export interface MemoryRecalledPayload {
  specification_id: string;
  requested_categories?: string[] | null;
  match_count: number;
  memory_ids: string[];
}

export interface Event {
  id: string;
  project_id: string;
  kind: "system" | "conversation";
  type: EventType;
  actor: Actor;
  payload: Record<string, unknown>;
  reason?: string | null;
  created_at: string;
}

export interface EventPayloadMap {
  "project.created": ProjectCreatedPayload;
  "project.archived": ProjectArchivedPayload;
  "task.created": TaskCreatedPayload;
  "task.assigned": TaskAssignedPayload;
  "task.started": TaskStartedPayload;
  "task.completed": TaskCompletedPayload;
  "task.failed": TaskFailedPayload;
  "task.retried": TaskRetriedPayload;
  "task.cancelled": TaskCancelledPayload;
  "task.state_changed": TaskStateChangedPayload;
  "task.recovered": TaskRecoveredPayload;
  "task.budget_exceeded": BudgetExceededPayload;
  "agent.created": AgentCreatedPayload;
  "agent.started": AgentStartedPayload;
  "agent.stopped": AgentStoppedPayload;
  "agent.state_changed": AgentStateChangedPayload;
  "agent.profile_updated": AgentProfileUpdatedPayload;
  "agent.coding_started": CodingStartedPayload;
  "agent.resolved": AgentResolvedPayload;
  "agent.hired": AgentHiredPayload;
  "agent.self_correction_triggered": AgentSelfCorrectionTriggeredPayload;
  "workspace.initialized": WorkspaceInitializedPayload;
  "code.changed": CodeChangedPayload;
  "branch.merged": BranchMergedPayload;
  "model.changed": ModelChangedPayload;
  "provider.changed": ProviderChangedPayload;
  "provider.retried": ProviderRetriedPayload;
  "workflow.review_started": ReviewStartedPayload;
  "workflow.review_completed": ReviewCompletedPayload;
  "workflow.bug_found": BugFoundPayload;
  "workflow.deployment_started": DeploymentStartedPayload;
  "workflow.deployment_completed": DeploymentCompletedPayload;
  "workflow.deployment_failed": DeploymentFailedPayload;
  "execution.started": ExecutionStartedPayload;
  "execution.completed": ExecutionCompletedPayload;
  "approval.requested": ApprovalRequestedPayload;
  "approval.granted": ApprovalGrantedPayload;
  "approval.rejected": ApprovalRejectedPayload;
  "approval.changes_requested": ApprovalChangesRequestedPayload;
  "system.heartbeat": SystemHeartbeatPayload;
  "conversation.message": ConversationMessagePayload;
  "conversation.message.delta": ConversationMessageDeltaPayload;
  "specification.requested": SpecificationRequestedPayload;
  "specification.turn_posted": SpecificationTurnPostedPayload;
  "specification.clarification_requested": SpecificationClarificationRequestedPayload;
  "specification.clarification_answered": SpecificationClarificationAnsweredPayload;
  "specification.ready_for_review": SpecificationReadyPayload;
  "specification.approved": SpecificationApprovedPayload;
  "specification.revision_requested": SpecificationRevisionRequestedPayload;
  "specification.rejected": SpecificationRejectedPayload;
  "specification.cancelled": SpecificationCancelledPayload;
  "specification.failed": SpecificationFailedPayload;
  "memory.recorded": MemoryRecordedPayload;
  "memory.recalled": MemoryRecalledPayload;
}

export const TASK_STATE_STATUS_WORD: Record<TaskState, StatusWord> = {
  [TaskState.CREATED]: StatusWord.PLANNING,
  [TaskState.ASSIGNED]: StatusWord.PLANNING,
  [TaskState.IN_PROGRESS]: StatusWord.DEVELOPING,
  [TaskState.IN_REVIEW]: StatusWord.REVIEWING,
  [TaskState.PENDING_APPROVAL]: StatusWord.NEEDS_DECISION,
  [TaskState.RETRYING]: StatusWord.DEVELOPING,
  [TaskState.COMPLETED]: StatusWord.COMPLETED,
  [TaskState.FAILED]: StatusWord.FAILED,
  [TaskState.CANCELLED]: StatusWord.CANCELLED,
  [TaskState.BLOCKED]: StatusWord.BLOCKED,
};

export const AGENT_STATE_STATUS_WORD: Record<AgentState, StatusWord> = {
  [AgentState.IDLE]: StatusWord.IDLE,
  [AgentState.ASSIGNED]: StatusWord.PLANNING,
  [AgentState.PLANNING]: StatusWord.PLANNING,
  [AgentState.WORKING]: StatusWord.DEVELOPING,
  [AgentState.WAITING_REVIEW]: StatusWord.REVIEWING,
  [AgentState.BLOCKED]: StatusWord.BLOCKED,
  [AgentState.COMPLETED]: StatusWord.COMPLETED,
  [AgentState.FAILED]: StatusWord.FAILED,
};
