#!/usr/bin/env python
"""Generate TypeScript types from the Pydantic v2 event contracts.

Hand-rolled instead of pydantic2ts/datamodel-code-generator: those need a
node subprocess or extra deps that may not be available offline. Walking
`model_fields` directly is a few dozen lines and has zero extra
dependencies, which matters more here than generality.

Run: python scripts/generate_ts_schemas.py
Output: packages/event-schemas/ts/index.ts (frontend imports from here).
"""

from __future__ import annotations

import enum
import sys
import types
import typing
from datetime import datetime
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / "apps" / "api"))

from pydantic import BaseModel  # noqa: E402

from app.core.events.base import Actor, Event  # noqa: E402
from app.core.events.contracts import PAYLOAD_MODELS  # noqa: E402
from app.core.events.types import EventType  # noqa: E402
from app.core.lifecycle.agent_states import AgentState  # noqa: E402
from app.core.lifecycle.task_states import TaskState  # noqa: E402

OUT_DIR = REPO_ROOT / "packages" / "event-schemas" / "ts"

# Models to emit, in dependency order (referenced-before-referencing).
ENUMS: list[type[enum.Enum]] = [EventType, AgentState, TaskState]
MODELS: list[type[BaseModel]] = [Actor, *PAYLOAD_MODELS.values(), Event]


def ts_type(annotation: typing.Any) -> str:
    """Best-effort Python type annotation -> TypeScript type string."""
    if annotation is type(None):
        return "null"
    if annotation is str:
        return "string"
    if annotation in (int, float):
        return "number"
    if annotation is bool:
        return "boolean"
    if annotation is datetime:
        return "string"
    if annotation is typing.Any:
        return "unknown"

    origin = typing.get_origin(annotation)

    if origin in (typing.Union, types.UnionType):
        return " | ".join(ts_type(a) for a in typing.get_args(annotation))

    if origin is typing.Literal:
        return " | ".join(
            f'"{a}"' if isinstance(a, str) else str(a).lower()
            for a in typing.get_args(annotation)
        )

    if origin in (list, typing.List):
        (item,) = typing.get_args(annotation) or (typing.Any,)
        return f"{ts_type(item)}[]"

    if origin in (dict, typing.Dict):
        args = typing.get_args(annotation)
        value = args[1] if len(args) == 2 else typing.Any
        return f"Record<string, {ts_type(value)}>"

    if isinstance(annotation, type) and issubclass(annotation, enum.Enum):
        return annotation.__name__

    if isinstance(annotation, type) and issubclass(annotation, BaseModel):
        return annotation.__name__

    return "unknown"


def emit_enum(model: type[enum.Enum]) -> str:
    members = "\n".join(f'  {m.name} = "{m.value}",' for m in model)
    return f"export enum {model.__name__} {{\n{members}\n}}\n"


def emit_interface(model: type[BaseModel]) -> str:
    lines = [f"export interface {model.__name__} {{"]
    for name, field in model.model_fields.items():
        annotation = field.annotation
        optional = field.is_required() is False and _is_optional(annotation)
        lines.append(f"  {name}{'?' if optional else ''}: {ts_type(annotation)};")
    lines.append("}\n")
    return "\n".join(lines)


def _is_optional(annotation: typing.Any) -> bool:
    origin = typing.get_origin(annotation)
    if origin in (typing.Union, types.UnionType):
        return type(None) in typing.get_args(annotation)
    return False


def emit_payload_map() -> str:
    lines = ["export interface EventPayloadMap {"]
    for event_type, model in PAYLOAD_MODELS.items():
        lines.append(f'  "{event_type.value}": {model.__name__};')
    lines.append("}\n")
    return "\n".join(lines)


def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    header = (
        "// AUTO-GENERATED by scripts/generate_ts_schemas.py — do not edit by hand.\n"
        "// Source of truth: apps/api/app/core/events/*.py\n\n"
    )
    parts = [header]
    for e in ENUMS:
        parts.append(emit_enum(e))
    for m in MODELS:
        parts.append(emit_interface(m))
    parts.append(emit_payload_map())

    out_file = OUT_DIR / "index.ts"
    out_file.write_text("\n".join(parts), encoding="utf-8")
    print(f"wrote {out_file.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
